version: '2.1'
volumes:
  # When using bind mount, make sure all these folders exists
  repo-volume:
    driver_opts:
      type: none
      device: ${PWD}/../../
      o: bind
  mapfiles-volume:
    driver_opts:
      type: none
      device: ${PWD}/mapfiles
      o: bind

services:
  mapserver:
    volumes:
      - repo-volume:/opt/inasafe-fba
      - mapfiles-volume:/etc/mapserver
    ports:
      - "${MAPSERVER_PORT}:80"
  django-web:
    ports:
      - "${DJANGO_PORT}:8080"
